name: Build Timer App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up devkitPro manually
      run: |
        sudo mkdir -p /etc/apt/keyrings
        curl -fsSL https://apt.devkitpro.org/devkitpro-pub.gpg | gpg --dearmor | sudo tee /etc/apt/keyrings/devkitpro.gpg > /dev/null
        echo "deb [signed-by=/etc/apt/keyrings/devkitpro.gpg] https://apt.devkitpro.org stable main" | sudo tee /etc/apt/sources.list.d/devkitpro.list
        sudo apt update
        sudo apt install -y devkitpro-pacman
        sudo /opt/devkitpro/pacman/bin/pacman-key --init
        sudo /opt/devkitpro/pacman/bin/pacman-key --populate
        sudo /opt/devkitpro/pacman/bin/pacman -Sy --noconfirm switch-dev

    - name: Build .nro
      run: |
        export DEVKITPRO=/opt/devkitpro
        export DEVKITARM=$DEVKITPRO/devkitARM
        export DEVKITA64=$DEVKITPRO/devkitA64
        make

    - name: Upload NRO
      uses: actions/upload-artifact@v4
      with:
        name: timer_app.nro
        path: output/timer_app.nro