name: Build NRO

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up devkitPro
      run: |
        sudo apt update
        sudo apt install -y devkitpro-pacman
        sudo dkp-pacman -Sy --noconfirm switch-dev

    - name: Build project
      run: make

    - name: Upload NRO
      uses: actions/upload-artifact@v4
      with:
        name: timer_app_nro
        path: output/timer_app.nro
