jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install devkitPro using official installer
      run: |
        sudo apt update
        sudo apt install -y curl tar xz-utils
        curl -LO https://downloads.devkitpro.org/devkitproinstaller
        chmod +x devkitproinstaller
        sudo ./devkitproinstaller -s switch-dev

    - name: Set environment variables
      run: |
        echo "DEVKITPRO=/opt/devkitpro" >> $GITHUB_ENV
        echo "DEVKITA64=/opt/devkitpro/devkitA64" >> $GITHUB_ENV
        echo "DEVKITARM=/opt/devkitpro/devkitARM" >> $GITHUB_ENV

    - name: Build .nro
      run: |
        make